version: '2'

services:
  mongo:
    image: mongo:4.1
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_SECRET}
    volumes:
      - ${MONGO_DATA}:/data/db
      - ${MONGO_BACKUP}:/backup
    networks:
      - collector-net

  collector:
    build: backend
    image: drypa/receipt-collector:latest
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_LOGIN=${MONGO_LOGIN}
      - MONGO_SECRET=${MONGO_SECRET}
      - NALOGRU_LOGIN=${NALOGRU_LOGIN}
      - NALOGRU_PASS=${NALOGRU_PASS}
      - GET_RECEIPT_WORKER_INTERVAL=5m
      - NALOGRU_BASE_ADDR=https://irkkt-mobile.nalog.ru:8888
      - WORKER_START_HOUR=20
      - WORKER_END_HOUR=5
    networks:
      - collector-net
    volumes:
      - "${SSL_CERTS_PATH}:/usr/share/receipts/ssl/certs/"

  bot:
    build: bot
    image: drypa/receipt-telegram-bot:latest
    restart: always
    depends_on:
      - mongo
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BACKEND_URL=http://collector:8888
    networks:
      - collector-net
    volumes:
      - "${SSL_CERTS_PATH}:/usr/share/receipts/ssl/certs/"

  gateway:
    build: webapp
    image: drypa/receipt-frontend:latest
    restart: always
    ports:
      - "443:443"
    volumes:
      - "./ssl:/etc/nginx/ssl"
    networks:
      - collector-net
networks:
  collector-net:
