services:
  mongo:
    image: mongo:4.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_SECRET}
    volumes:
      - "./data:/data/db"
      - ${MONGO_BACKUP}:/backup
    ports:
      - "27017:27017"
  pg:
    image: postgres:18.0
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${PG_LOGIN}
      POSTGRES_PASSWORD: ${PG_SECRET}
#    volumes:
#      - "./postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  nginx:
    image: nginx:alpine
    container_name: receipt-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.dev.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"