version: '2'

services:
  mongo:
    image: mongo:4.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_SECRET}
    volumes:
      - ${MONGO_DATA}:/data/db
    networks:
      - collector-net

  collector:
    build: backend
    image: receipt_collector:latest
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_LOGIN=${MONGO_LOGIN}
      - MONGO_SECRET=${MONGO_SECRET}
      - NALOGRU_LOGIN=${NALOGRU_LOGIN}
      - NALOGRU_PASS=${NALOGRU_PASS}
      - GET_RECEIPT_WORKER_INTERVAL=5s
    networks:
      - collector-net

  gateway:
    build: webapp
    ports:
      - "443:443"
    volumes:
      - "./ssl:/etc/nginx/ssl"
    networks:
      - collector-net
networks:
  collector-net:
