version: '2'
services:
  mongo:
    image: mongo:4.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_SECRET}
    volumes:
      - "./data:/data/db"
      - ${MONGO_BACKUP}:/backup
    ports:
      - "27017:27017"
