version: '2'

services:
  mongo:
    container_name: receipt-mongo
    image: mongo:4.1
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_SECRET}
    volumes:
      - ${MONGO_DATA}:/data/db
      - ${MONGO_BACKUP}:/backup
    networks:
      - collector-net

  collector:
    container_name: receipt-collector
    build: backend
    image: drypa/receipt-collector:latest
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_LOGIN=${MONGO_LOGIN}
      - MONGO_SECRET=${MONGO_SECRET}
      - GET_RECEIPT_WORKER_INTERVAL=15m
      - NALOGRU_BASE_ADDR=https://irkkt-mobile.nalog.ru:8888
    networks:
      - collector-net
    volumes:
      - "${SSL_CERTS_PATH}:/usr/share/receipts/ssl/certs/"
      - "${RAW_TICKET_DUMP_PATH}:/var/lib/receipts/raw/"
      - "${GET_TICKET_ERROR_PATH}:/var/lib/receipts/error/"

  bot:
    container_name: receipt-bot
    build: bot
    image: drypa/receipt-telegram-bot:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BACKEND_GRPC_ADDR=collector:15000
      - REPORTS_GRPC_ADDR=collector:15001
    networks:
      - collector-net
    volumes:
      - "${SSL_CERTS_PATH}:/usr/share/receipts/ssl/certs/"
networks:
  collector-net:
