// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts.proto

package inside_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetLoginLinkRequest struct {
	TelegramId           int32    `protobuf:"varint,1,opt,name=telegramId,proto3" json:"telegramId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLoginLinkRequest) Reset()         { *m = GetLoginLinkRequest{} }
func (m *GetLoginLinkRequest) String() string { return proto.CompactTextString(m) }
func (*GetLoginLinkRequest) ProtoMessage()    {}
func (*GetLoginLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{0}
}

func (m *GetLoginLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLoginLinkRequest.Unmarshal(m, b)
}
func (m *GetLoginLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLoginLinkRequest.Marshal(b, m, deterministic)
}
func (m *GetLoginLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLoginLinkRequest.Merge(m, src)
}
func (m *GetLoginLinkRequest) XXX_Size() int {
	return xxx_messageInfo_GetLoginLinkRequest.Size(m)
}
func (m *GetLoginLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLoginLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLoginLinkRequest proto.InternalMessageInfo

func (m *GetLoginLinkRequest) GetTelegramId() int32 {
	if m != nil {
		return m.TelegramId
	}
	return 0
}

type GetUserRequest struct {
	TelegramId           int32    `protobuf:"varint,1,opt,name=telegramId,proto3" json:"telegramId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{1}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetTelegramId() int32 {
	if m != nil {
		return m.TelegramId
	}
	return 0
}

type LoginLinkResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Expiration           int64    `protobuf:"varint,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginLinkResponse) Reset()         { *m = LoginLinkResponse{} }
func (m *LoginLinkResponse) String() string { return proto.CompactTextString(m) }
func (*LoginLinkResponse) ProtoMessage()    {}
func (*LoginLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{2}
}

func (m *LoginLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginLinkResponse.Unmarshal(m, b)
}
func (m *LoginLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginLinkResponse.Marshal(b, m, deterministic)
}
func (m *LoginLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginLinkResponse.Merge(m, src)
}
func (m *LoginLinkResponse) XXX_Size() int {
	return xxx_messageInfo_LoginLinkResponse.Size(m)
}
func (m *LoginLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginLinkResponse proto.InternalMessageInfo

func (m *LoginLinkResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *LoginLinkResponse) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type User struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TelegramId           int32    `protobuf:"varint,2,opt,name=telegramId,proto3" json:"telegramId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetTelegramId() int32 {
	if m != nil {
		return m.TelegramId
	}
	return 0
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{4}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{5}
}

func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(m, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserRegistrationRequest struct {
	TelegramId           int32    `protobuf:"varint,1,opt,name=telegramId,proto3" json:"telegramId,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegistrationRequest) Reset()         { *m = UserRegistrationRequest{} }
func (m *UserRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegistrationRequest) ProtoMessage()    {}
func (*UserRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{6}
}

func (m *UserRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegistrationRequest.Unmarshal(m, b)
}
func (m *UserRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *UserRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegistrationRequest.Merge(m, src)
}
func (m *UserRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegistrationRequest.Size(m)
}
func (m *UserRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegistrationRequest proto.InternalMessageInfo

func (m *UserRegistrationRequest) GetTelegramId() int32 {
	if m != nil {
		return m.TelegramId
	}
	return 0
}

func (m *UserRegistrationRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type UserRegistrationResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegistrationResponse) Reset()         { *m = UserRegistrationResponse{} }
func (m *UserRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*UserRegistrationResponse) ProtoMessage()    {}
func (*UserRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{7}
}

func (m *UserRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegistrationResponse.Unmarshal(m, b)
}
func (m *UserRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegistrationResponse.Marshal(b, m, deterministic)
}
func (m *UserRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegistrationResponse.Merge(m, src)
}
func (m *UserRegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_UserRegistrationResponse.Size(m)
}
func (m *UserRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegistrationResponse proto.InternalMessageInfo

func (m *UserRegistrationResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type PhoneVerificationRequest struct {
	TelegramId           int32    `protobuf:"varint,1,opt,name=telegramId,proto3" json:"telegramId,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneVerificationRequest) Reset()         { *m = PhoneVerificationRequest{} }
func (m *PhoneVerificationRequest) String() string { return proto.CompactTextString(m) }
func (*PhoneVerificationRequest) ProtoMessage()    {}
func (*PhoneVerificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{8}
}

func (m *PhoneVerificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneVerificationRequest.Unmarshal(m, b)
}
func (m *PhoneVerificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneVerificationRequest.Marshal(b, m, deterministic)
}
func (m *PhoneVerificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneVerificationRequest.Merge(m, src)
}
func (m *PhoneVerificationRequest) XXX_Size() int {
	return xxx_messageInfo_PhoneVerificationRequest.Size(m)
}
func (m *PhoneVerificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneVerificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneVerificationRequest proto.InternalMessageInfo

func (m *PhoneVerificationRequest) GetTelegramId() int32 {
	if m != nil {
		return m.TelegramId
	}
	return 0
}

func (m *PhoneVerificationRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*GetLoginLinkRequest)(nil), "inside_api.GetLoginLinkRequest")
	proto.RegisterType((*GetUserRequest)(nil), "inside_api.GetUserRequest")
	proto.RegisterType((*LoginLinkResponse)(nil), "inside_api.LoginLinkResponse")
	proto.RegisterType((*User)(nil), "inside_api.User")
	proto.RegisterType((*GetUserResponse)(nil), "inside_api.GetUserResponse")
	proto.RegisterType((*GetUsersResponse)(nil), "inside_api.GetUsersResponse")
	proto.RegisterType((*UserRegistrationRequest)(nil), "inside_api.UserRegistrationRequest")
	proto.RegisterType((*UserRegistrationResponse)(nil), "inside_api.UserRegistrationResponse")
	proto.RegisterType((*PhoneVerificationRequest)(nil), "inside_api.PhoneVerificationRequest")
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor_e1e7723af4c007b7) }

var fileDescriptor_e1e7723af4c007b7 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0xda, 0x0d, 0xfa, 0x06, 0xb3, 0x46, 0xd0, 0x9e, 0xa4, 0x04, 0x91, 0x9d, 0x8a,
	0x4c, 0x44, 0xf0, 0xe0, 0x4d, 0x86, 0x30, 0x86, 0x04, 0xf4, 0xe2, 0x41, 0xba, 0xf6, 0x59, 0x83,
	0x5b, 0x52, 0x93, 0x14, 0xfc, 0xf3, 0x25, 0x69, 0x98, 0xc5, 0x29, 0xcc, 0x5b, 0xfa, 0xde, 0xfb,
	0xbe, 0xef, 0xf7, 0x1e, 0x85, 0x49, 0x51, 0x96, 0xb2, 0x15, 0x46, 0xe7, 0x8d, 0x92, 0x46, 0x12,
	0xe0, 0x42, 0xf3, 0x0a, 0x5f, 0x8a, 0x86, 0xd3, 0x2b, 0x38, 0x9a, 0xa3, 0x59, 0xc8, 0x9a, 0x8b,
	0x05, 0x17, 0xef, 0x0c, 0x3f, 0x5a, 0xd4, 0x86, 0x9c, 0x02, 0x18, 0x5c, 0x63, 0xad, 0x8a, 0xcd,
	0x7d, 0x95, 0x06, 0x59, 0x30, 0x1d, 0xb2, 0x5e, 0x85, 0x5e, 0xc0, 0x64, 0x8e, 0xe6, 0x51, 0xa3,
	0xda, 0x57, 0x71, 0x07, 0x87, 0xbd, 0x14, 0xdd, 0x48, 0xa1, 0x91, 0x24, 0x10, 0xb6, 0x6a, 0xed,
	0xa6, 0x63, 0x66, 0x9f, 0xd6, 0x06, 0x3f, 0x1b, 0xae, 0x0a, 0xc3, 0xa5, 0x48, 0x07, 0x59, 0x30,
	0x0d, 0x59, 0xaf, 0x42, 0x6f, 0x21, 0xb2, 0xa9, 0xe4, 0x18, 0x46, 0xad, 0x46, 0xe5, 0xa3, 0x62,
	0xe6, 0xbf, 0x7e, 0x60, 0x0c, 0x76, 0x30, 0xae, 0xe1, 0x60, 0x0b, 0xee, 0x21, 0xce, 0x20, 0xb2,
	0x62, 0x67, 0x34, 0x9e, 0x25, 0xf9, 0xf7, 0x75, 0x72, 0x37, 0xe7, 0xba, 0xf4, 0x06, 0x12, 0x2f,
	0xd4, 0x5b, 0xe5, 0x39, 0x0c, 0x6d, 0x4f, 0xa7, 0x41, 0x16, 0xfe, 0x2a, 0xed, 0xda, 0xf4, 0x19,
	0x4e, 0xba, 0xc4, 0x9a, 0x6b, 0xd3, 0x2d, 0xb2, 0xe7, 0xd9, 0x48, 0x06, 0xe3, 0xe6, 0x4d, 0x0a,
	0x5c, 0xb6, 0x9b, 0x15, 0x2a, 0xb7, 0x50, 0xcc, 0xfa, 0x25, 0x3a, 0x83, 0x74, 0xd7, 0xdc, 0x03,
	0xfe, 0x71, 0x25, 0xba, 0x84, 0xf4, 0xc1, 0x5a, 0x3c, 0xa1, 0xe2, 0xaf, 0xbc, 0xfc, 0x17, 0x11,
	0x81, 0xa8, 0x94, 0x15, 0x7a, 0x14, 0xf7, 0x5e, 0x8d, 0xdc, 0x8f, 0x75, 0xf9, 0x15, 0x00, 0x00,
	0xff, 0xff, 0x30, 0xbd, 0x0d, 0x0a, 0x6a, 0x02, 0x00, 0x00,
}
