// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package inside

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountApiClient is the client API for AccountApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountApiClient interface {
	GetUsers(ctx context.Context, in *NoParams, opts ...grpc.CallOption) (*GetUsersResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type accountApiClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountApiClient(cc grpc.ClientConnInterface) AccountApiClient {
	return &accountApiClient{cc}
}

func (c *accountApiClient) GetUsers(ctx context.Context, in *NoParams, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/inside_api.AccountApi/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountApiClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/inside_api.AccountApi/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountApiServer is the server API for AccountApi service.
// All implementations must embed UnimplementedAccountApiServer
// for forward compatibility
type AccountApiServer interface {
	GetUsers(context.Context, *NoParams) (*GetUsersResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	mustEmbedUnimplementedAccountApiServer()
}

// UnimplementedAccountApiServer must be embedded to have forward compatible implementations.
type UnimplementedAccountApiServer struct {
}

func (UnimplementedAccountApiServer) GetUsers(context.Context, *NoParams) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedAccountApiServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedAccountApiServer) mustEmbedUnimplementedAccountApiServer() {}

// UnsafeAccountApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountApiServer will
// result in compilation errors.
type UnsafeAccountApiServer interface {
	mustEmbedUnimplementedAccountApiServer()
}

func RegisterAccountApiServer(s grpc.ServiceRegistrar, srv AccountApiServer) {
	s.RegisterService(&AccountApi_ServiceDesc, srv)
}

func _AccountApi_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountApiServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inside_api.AccountApi/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountApiServer).GetUsers(ctx, req.(*NoParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountApi_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountApiServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inside_api.AccountApi/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountApiServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountApi_ServiceDesc is the grpc.ServiceDesc for AccountApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inside_api.AccountApi",
	HandlerType: (*AccountApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _AccountApi_GetUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AccountApi_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contracts.proto",
}

// ReceiptApiClient is the client API for ReceiptApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReceiptApiClient interface {
	AddReceipt(ctx context.Context, in *AddReceiptRequest, opts ...grpc.CallOption) (*AddReceiptResponse, error)
	GetReceipts(ctx context.Context, in *GetReceiptsRequest, opts ...grpc.CallOption) (ReceiptApi_GetReceiptsClient, error)
	GetRawReceipt(ctx context.Context, in *GetRawReceiptReportRequest, opts ...grpc.CallOption) (*RawReceiptReport, error)
}

type receiptApiClient struct {
	cc grpc.ClientConnInterface
}

func NewReceiptApiClient(cc grpc.ClientConnInterface) ReceiptApiClient {
	return &receiptApiClient{cc}
}

func (c *receiptApiClient) AddReceipt(ctx context.Context, in *AddReceiptRequest, opts ...grpc.CallOption) (*AddReceiptResponse, error) {
	out := new(AddReceiptResponse)
	err := c.cc.Invoke(ctx, "/inside_api.ReceiptApi/AddReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiptApiClient) GetReceipts(ctx context.Context, in *GetReceiptsRequest, opts ...grpc.CallOption) (ReceiptApi_GetReceiptsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ReceiptApi_ServiceDesc.Streams[0], "/inside_api.ReceiptApi/GetReceipts", opts...)
	if err != nil {
		return nil, err
	}
	x := &receiptApiGetReceiptsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReceiptApi_GetReceiptsClient interface {
	Recv() (*Receipt, error)
	grpc.ClientStream
}

type receiptApiGetReceiptsClient struct {
	grpc.ClientStream
}

func (x *receiptApiGetReceiptsClient) Recv() (*Receipt, error) {
	m := new(Receipt)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *receiptApiClient) GetRawReceipt(ctx context.Context, in *GetRawReceiptReportRequest, opts ...grpc.CallOption) (*RawReceiptReport, error) {
	out := new(RawReceiptReport)
	err := c.cc.Invoke(ctx, "/inside_api.ReceiptApi/GetRawReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReceiptApiServer is the server API for ReceiptApi service.
// All implementations must embed UnimplementedReceiptApiServer
// for forward compatibility
type ReceiptApiServer interface {
	AddReceipt(context.Context, *AddReceiptRequest) (*AddReceiptResponse, error)
	GetReceipts(*GetReceiptsRequest, ReceiptApi_GetReceiptsServer) error
	GetRawReceipt(context.Context, *GetRawReceiptReportRequest) (*RawReceiptReport, error)
	mustEmbedUnimplementedReceiptApiServer()
}

// UnimplementedReceiptApiServer must be embedded to have forward compatible implementations.
type UnimplementedReceiptApiServer struct {
}

func (UnimplementedReceiptApiServer) AddReceipt(context.Context, *AddReceiptRequest) (*AddReceiptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReceipt not implemented")
}
func (UnimplementedReceiptApiServer) GetReceipts(*GetReceiptsRequest, ReceiptApi_GetReceiptsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetReceipts not implemented")
}
func (UnimplementedReceiptApiServer) GetRawReceipt(context.Context, *GetRawReceiptReportRequest) (*RawReceiptReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRawReceipt not implemented")
}
func (UnimplementedReceiptApiServer) mustEmbedUnimplementedReceiptApiServer() {}

// UnsafeReceiptApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReceiptApiServer will
// result in compilation errors.
type UnsafeReceiptApiServer interface {
	mustEmbedUnimplementedReceiptApiServer()
}

func RegisterReceiptApiServer(s grpc.ServiceRegistrar, srv ReceiptApiServer) {
	s.RegisterService(&ReceiptApi_ServiceDesc, srv)
}

func _ReceiptApi_AddReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiptApiServer).AddReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inside_api.ReceiptApi/AddReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiptApiServer).AddReceipt(ctx, req.(*AddReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiptApi_GetReceipts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetReceiptsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReceiptApiServer).GetReceipts(m, &receiptApiGetReceiptsServer{stream})
}

type ReceiptApi_GetReceiptsServer interface {
	Send(*Receipt) error
	grpc.ServerStream
}

type receiptApiGetReceiptsServer struct {
	grpc.ServerStream
}

func (x *receiptApiGetReceiptsServer) Send(m *Receipt) error {
	return x.ServerStream.SendMsg(m)
}

func _ReceiptApi_GetRawReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRawReceiptReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiptApiServer).GetRawReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inside_api.ReceiptApi/GetRawReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiptApiServer).GetRawReceipt(ctx, req.(*GetRawReceiptReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReceiptApi_ServiceDesc is the grpc.ServiceDesc for ReceiptApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReceiptApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inside_api.ReceiptApi",
	HandlerType: (*ReceiptApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddReceipt",
			Handler:    _ReceiptApi_AddReceipt_Handler,
		},
		{
			MethodName: "GetRawReceipt",
			Handler:    _ReceiptApi_GetRawReceipt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetReceipts",
			Handler:       _ReceiptApi_GetReceipts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "contracts.proto",
}

// InternalApiClient is the client API for InternalApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalApiClient interface {
	RegisterUser(ctx context.Context, in *UserRegistrationRequest, opts ...grpc.CallOption) (*UserRegistrationResponse, error)
	VerifyPhone(ctx context.Context, in *PhoneVerificationRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	GetFirstUnckeckedRequest(ctx context.Context, in *NoParams, opts ...grpc.CallOption) (*ReceiptRequest, error)
	SetRequestStatus(ctx context.Context, in *SetRequestStatusRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	GetFirstRequestWithStatus(ctx context.Context, in *QueryByStatus, opts ...grpc.CallOption) (*ReceiptRequest, error)
	SetTicketId(ctx context.Context, in *SetTicketIdRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	AddRawTicket(ctx context.Context, in *AddRawTicketRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (InternalApi_GetDevicesClient, error)
	UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
}

type internalApiClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalApiClient(cc grpc.ClientConnInterface) InternalApiClient {
	return &internalApiClient{cc}
}

func (c *internalApiClient) RegisterUser(ctx context.Context, in *UserRegistrationRequest, opts ...grpc.CallOption) (*UserRegistrationResponse, error) {
	out := new(UserRegistrationResponse)
	err := c.cc.Invoke(ctx, "/inside_api.InternalApi/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalApiClient) VerifyPhone(ctx context.Context, in *PhoneVerificationRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/inside_api.InternalApi/VerifyPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalApiClient) GetFirstUnckeckedRequest(ctx context.Context, in *NoParams, opts ...grpc.CallOption) (*ReceiptRequest, error) {
	out := new(ReceiptRequest)
	err := c.cc.Invoke(ctx, "/inside_api.InternalApi/GetFirstUnckeckedRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalApiClient) SetRequestStatus(ctx context.Context, in *SetRequestStatusRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/inside_api.InternalApi/SetRequestStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalApiClient) GetFirstRequestWithStatus(ctx context.Context, in *QueryByStatus, opts ...grpc.CallOption) (*ReceiptRequest, error) {
	out := new(ReceiptRequest)
	err := c.cc.Invoke(ctx, "/inside_api.InternalApi/GetFirstRequestWithStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalApiClient) SetTicketId(ctx context.Context, in *SetTicketIdRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/inside_api.InternalApi/SetTicketId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalApiClient) AddRawTicket(ctx context.Context, in *AddRawTicketRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/inside_api.InternalApi/AddRawTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalApiClient) GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (InternalApi_GetDevicesClient, error) {
	stream, err := c.cc.NewStream(ctx, &InternalApi_ServiceDesc.Streams[0], "/inside_api.InternalApi/GetDevices", opts...)
	if err != nil {
		return nil, err
	}
	x := &internalApiGetDevicesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InternalApi_GetDevicesClient interface {
	Recv() (*Device, error)
	grpc.ClientStream
}

type internalApiGetDevicesClient struct {
	grpc.ClientStream
}

func (x *internalApiGetDevicesClient) Recv() (*Device, error) {
	m := new(Device)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *internalApiClient) UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/inside_api.InternalApi/UpdateDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalApiServer is the server API for InternalApi service.
// All implementations must embed UnimplementedInternalApiServer
// for forward compatibility
type InternalApiServer interface {
	RegisterUser(context.Context, *UserRegistrationRequest) (*UserRegistrationResponse, error)
	VerifyPhone(context.Context, *PhoneVerificationRequest) (*ErrorResponse, error)
	GetFirstUnckeckedRequest(context.Context, *NoParams) (*ReceiptRequest, error)
	SetRequestStatus(context.Context, *SetRequestStatusRequest) (*ErrorResponse, error)
	GetFirstRequestWithStatus(context.Context, *QueryByStatus) (*ReceiptRequest, error)
	SetTicketId(context.Context, *SetTicketIdRequest) (*ErrorResponse, error)
	AddRawTicket(context.Context, *AddRawTicketRequest) (*ErrorResponse, error)
	GetDevices(*GetDevicesRequest, InternalApi_GetDevicesServer) error
	UpdateDevice(context.Context, *UpdateDeviceRequest) (*ErrorResponse, error)
	mustEmbedUnimplementedInternalApiServer()
}

// UnimplementedInternalApiServer must be embedded to have forward compatible implementations.
type UnimplementedInternalApiServer struct {
}

func (UnimplementedInternalApiServer) RegisterUser(context.Context, *UserRegistrationRequest) (*UserRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedInternalApiServer) VerifyPhone(context.Context, *PhoneVerificationRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPhone not implemented")
}
func (UnimplementedInternalApiServer) GetFirstUnckeckedRequest(context.Context, *NoParams) (*ReceiptRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFirstUnckeckedRequest not implemented")
}
func (UnimplementedInternalApiServer) SetRequestStatus(context.Context, *SetRequestStatusRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRequestStatus not implemented")
}
func (UnimplementedInternalApiServer) GetFirstRequestWithStatus(context.Context, *QueryByStatus) (*ReceiptRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFirstRequestWithStatus not implemented")
}
func (UnimplementedInternalApiServer) SetTicketId(context.Context, *SetTicketIdRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTicketId not implemented")
}
func (UnimplementedInternalApiServer) AddRawTicket(context.Context, *AddRawTicketRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRawTicket not implemented")
}
func (UnimplementedInternalApiServer) GetDevices(*GetDevicesRequest, InternalApi_GetDevicesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDevices not implemented")
}
func (UnimplementedInternalApiServer) UpdateDevice(context.Context, *UpdateDeviceRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDevice not implemented")
}
func (UnimplementedInternalApiServer) mustEmbedUnimplementedInternalApiServer() {}

// UnsafeInternalApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalApiServer will
// result in compilation errors.
type UnsafeInternalApiServer interface {
	mustEmbedUnimplementedInternalApiServer()
}

func RegisterInternalApiServer(s grpc.ServiceRegistrar, srv InternalApiServer) {
	s.RegisterService(&InternalApi_ServiceDesc, srv)
}

func _InternalApi_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalApiServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inside_api.InternalApi/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalApiServer).RegisterUser(ctx, req.(*UserRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalApi_VerifyPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalApiServer).VerifyPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inside_api.InternalApi/VerifyPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalApiServer).VerifyPhone(ctx, req.(*PhoneVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalApi_GetFirstUnckeckedRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalApiServer).GetFirstUnckeckedRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inside_api.InternalApi/GetFirstUnckeckedRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalApiServer).GetFirstUnckeckedRequest(ctx, req.(*NoParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalApi_SetRequestStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequestStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalApiServer).SetRequestStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inside_api.InternalApi/SetRequestStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalApiServer).SetRequestStatus(ctx, req.(*SetRequestStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalApi_GetFirstRequestWithStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryByStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalApiServer).GetFirstRequestWithStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inside_api.InternalApi/GetFirstRequestWithStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalApiServer).GetFirstRequestWithStatus(ctx, req.(*QueryByStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalApi_SetTicketId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTicketIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalApiServer).SetTicketId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inside_api.InternalApi/SetTicketId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalApiServer).SetTicketId(ctx, req.(*SetTicketIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalApi_AddRawTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRawTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalApiServer).AddRawTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inside_api.InternalApi/AddRawTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalApiServer).AddRawTicket(ctx, req.(*AddRawTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalApi_GetDevices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDevicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InternalApiServer).GetDevices(m, &internalApiGetDevicesServer{stream})
}

type InternalApi_GetDevicesServer interface {
	Send(*Device) error
	grpc.ServerStream
}

type internalApiGetDevicesServer struct {
	grpc.ServerStream
}

func (x *internalApiGetDevicesServer) Send(m *Device) error {
	return x.ServerStream.SendMsg(m)
}

func _InternalApi_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalApiServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inside_api.InternalApi/UpdateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalApiServer).UpdateDevice(ctx, req.(*UpdateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalApi_ServiceDesc is the grpc.ServiceDesc for InternalApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inside_api.InternalApi",
	HandlerType: (*InternalApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _InternalApi_RegisterUser_Handler,
		},
		{
			MethodName: "VerifyPhone",
			Handler:    _InternalApi_VerifyPhone_Handler,
		},
		{
			MethodName: "GetFirstUnckeckedRequest",
			Handler:    _InternalApi_GetFirstUnckeckedRequest_Handler,
		},
		{
			MethodName: "SetRequestStatus",
			Handler:    _InternalApi_SetRequestStatus_Handler,
		},
		{
			MethodName: "GetFirstRequestWithStatus",
			Handler:    _InternalApi_GetFirstRequestWithStatus_Handler,
		},
		{
			MethodName: "SetTicketId",
			Handler:    _InternalApi_SetTicketId_Handler,
		},
		{
			MethodName: "AddRawTicket",
			Handler:    _InternalApi_AddRawTicket_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _InternalApi_UpdateDevice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDevices",
			Handler:       _InternalApi_GetDevices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "contracts.proto",
}
