// Code generated by protoc-gen-go. DO NOT EDIT.
// source: receipts.proto

package inside_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddReceiptRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReceiptQr            string   `protobuf:"bytes,2,opt,name=receiptQr,proto3" json:"receiptQr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReceiptRequest) Reset()         { *m = AddReceiptRequest{} }
func (m *AddReceiptRequest) String() string { return proto.CompactTextString(m) }
func (*AddReceiptRequest) ProtoMessage()    {}
func (*AddReceiptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef1c006035b8d22c, []int{0}
}

func (m *AddReceiptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReceiptRequest.Unmarshal(m, b)
}
func (m *AddReceiptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReceiptRequest.Marshal(b, m, deterministic)
}
func (m *AddReceiptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReceiptRequest.Merge(m, src)
}
func (m *AddReceiptRequest) XXX_Size() int {
	return xxx_messageInfo_AddReceiptRequest.Size(m)
}
func (m *AddReceiptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReceiptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddReceiptRequest proto.InternalMessageInfo

func (m *AddReceiptRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddReceiptRequest) GetReceiptQr() string {
	if m != nil {
		return m.ReceiptQr
	}
	return ""
}

type AddReceiptResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReceiptResponse) Reset()         { *m = AddReceiptResponse{} }
func (m *AddReceiptResponse) String() string { return proto.CompactTextString(m) }
func (*AddReceiptResponse) ProtoMessage()    {}
func (*AddReceiptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef1c006035b8d22c, []int{1}
}

func (m *AddReceiptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReceiptResponse.Unmarshal(m, b)
}
func (m *AddReceiptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReceiptResponse.Marshal(b, m, deterministic)
}
func (m *AddReceiptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReceiptResponse.Merge(m, src)
}
func (m *AddReceiptResponse) XXX_Size() int {
	return xxx_messageInfo_AddReceiptResponse.Size(m)
}
func (m *AddReceiptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReceiptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddReceiptResponse proto.InternalMessageInfo

func (m *AddReceiptResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetReceiptsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReceiptsRequest) Reset()         { *m = GetReceiptsRequest{} }
func (m *GetReceiptsRequest) String() string { return proto.CompactTextString(m) }
func (*GetReceiptsRequest) ProtoMessage()    {}
func (*GetReceiptsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef1c006035b8d22c, []int{2}
}

func (m *GetReceiptsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReceiptsRequest.Unmarshal(m, b)
}
func (m *GetReceiptsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReceiptsRequest.Marshal(b, m, deterministic)
}
func (m *GetReceiptsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReceiptsRequest.Merge(m, src)
}
func (m *GetReceiptsRequest) XXX_Size() int {
	return xxx_messageInfo_GetReceiptsRequest.Size(m)
}
func (m *GetReceiptsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReceiptsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReceiptsRequest proto.InternalMessageInfo

func (m *GetReceiptsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Receipt struct {
	DateTime             int64    `protobuf:"varint,1,opt,name=DateTime,proto3" json:"DateTime,omitempty"`
	CashTotalSum         int64    `protobuf:"varint,2,opt,name=CashTotalSum,proto3" json:"CashTotalSum,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=Code,proto3" json:"Code,omitempty"`
	CreditSum            int64    `protobuf:"varint,4,opt,name=CreditSum,proto3" json:"CreditSum,omitempty"`
	EcashTotalSum        int64    `protobuf:"varint,5,opt,name=EcashTotalSum,proto3" json:"EcashTotalSum,omitempty"`
	FiscalDocumentNumber int32    `protobuf:"varint,6,opt,name=FiscalDocumentNumber,proto3" json:"FiscalDocumentNumber,omitempty"`
	FnsUrl               string   `protobuf:"bytes,9,opt,name=FnsUrl,proto3" json:"FnsUrl,omitempty"`
	Items                []*Item  `protobuf:"bytes,10,rep,name=Items,proto3" json:"Items,omitempty"`
	UserInn              string   `protobuf:"bytes,11,opt,name=UserInn,proto3" json:"UserInn,omitempty"`
	Nds10                int64    `protobuf:"varint,12,opt,name=Nds10,proto3" json:"Nds10,omitempty"`
	Nds18                int64    `protobuf:"varint,13,opt,name=Nds18,proto3" json:"Nds18,omitempty"`
	OperationType        int32    `protobuf:"varint,14,opt,name=OperationType,proto3" json:"OperationType,omitempty"`
	Operator             string   `protobuf:"bytes,15,opt,name=Operator,proto3" json:"Operator,omitempty"`
	PrepaidSum           int64    `protobuf:"varint,16,opt,name=PrepaidSum,proto3" json:"PrepaidSum,omitempty"`
	ProvisionSum         int64    `protobuf:"varint,17,opt,name=ProvisionSum,proto3" json:"ProvisionSum,omitempty"`
	RequestNumber        int32    `protobuf:"varint,18,opt,name=RequestNumber,proto3" json:"RequestNumber,omitempty"`
	RetailPlace          string   `protobuf:"bytes,19,opt,name=RetailPlace,proto3" json:"RetailPlace,omitempty"`
	RetailPlaceAddress   string   `protobuf:"bytes,20,opt,name=RetailPlaceAddress,proto3" json:"RetailPlaceAddress,omitempty"`
	TotalSum             int64    `protobuf:"varint,21,opt,name=TotalSum,proto3" json:"TotalSum,omitempty"`
	User                 string   `protobuf:"bytes,22,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef1c006035b8d22c, []int{3}
}

func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetDateTime() int64 {
	if m != nil {
		return m.DateTime
	}
	return 0
}

func (m *Receipt) GetCashTotalSum() int64 {
	if m != nil {
		return m.CashTotalSum
	}
	return 0
}

func (m *Receipt) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Receipt) GetCreditSum() int64 {
	if m != nil {
		return m.CreditSum
	}
	return 0
}

func (m *Receipt) GetEcashTotalSum() int64 {
	if m != nil {
		return m.EcashTotalSum
	}
	return 0
}

func (m *Receipt) GetFiscalDocumentNumber() int32 {
	if m != nil {
		return m.FiscalDocumentNumber
	}
	return 0
}

func (m *Receipt) GetFnsUrl() string {
	if m != nil {
		return m.FnsUrl
	}
	return ""
}

func (m *Receipt) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Receipt) GetUserInn() string {
	if m != nil {
		return m.UserInn
	}
	return ""
}

func (m *Receipt) GetNds10() int64 {
	if m != nil {
		return m.Nds10
	}
	return 0
}

func (m *Receipt) GetNds18() int64 {
	if m != nil {
		return m.Nds18
	}
	return 0
}

func (m *Receipt) GetOperationType() int32 {
	if m != nil {
		return m.OperationType
	}
	return 0
}

func (m *Receipt) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Receipt) GetPrepaidSum() int64 {
	if m != nil {
		return m.PrepaidSum
	}
	return 0
}

func (m *Receipt) GetProvisionSum() int64 {
	if m != nil {
		return m.ProvisionSum
	}
	return 0
}

func (m *Receipt) GetRequestNumber() int32 {
	if m != nil {
		return m.RequestNumber
	}
	return 0
}

func (m *Receipt) GetRetailPlace() string {
	if m != nil {
		return m.RetailPlace
	}
	return ""
}

func (m *Receipt) GetRetailPlaceAddress() string {
	if m != nil {
		return m.RetailPlaceAddress
	}
	return ""
}

func (m *Receipt) GetTotalSum() int64 {
	if m != nil {
		return m.TotalSum
	}
	return 0
}

func (m *Receipt) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type Item struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Nds                  int32    `protobuf:"varint,2,opt,name=Nds,proto3" json:"Nds,omitempty"`
	NdsSum               int64    `protobuf:"varint,3,opt,name=NdsSum,proto3" json:"NdsSum,omitempty"`
	PaymentType          int32    `protobuf:"varint,4,opt,name=PaymentType,proto3" json:"PaymentType,omitempty"`
	Price                int64    `protobuf:"varint,5,opt,name=Price,proto3" json:"Price,omitempty"`
	Quantity             float32  `protobuf:"fixed32,6,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Sum                  int64    `protobuf:"varint,7,opt,name=Sum,proto3" json:"Sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef1c006035b8d22c, []int{4}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetNds() int32 {
	if m != nil {
		return m.Nds
	}
	return 0
}

func (m *Item) GetNdsSum() int64 {
	if m != nil {
		return m.NdsSum
	}
	return 0
}

func (m *Item) GetPaymentType() int32 {
	if m != nil {
		return m.PaymentType
	}
	return 0
}

func (m *Item) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Item) GetSum() int64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func init() {
	proto.RegisterType((*AddReceiptRequest)(nil), "inside_api.AddReceiptRequest")
	proto.RegisterType((*AddReceiptResponse)(nil), "inside_api.AddReceiptResponse")
	proto.RegisterType((*GetReceiptsRequest)(nil), "inside_api.GetReceiptsRequest")
	proto.RegisterType((*Receipt)(nil), "inside_api.Receipt")
	proto.RegisterType((*Item)(nil), "inside_api.Item")
}

func init() { proto.RegisterFile("receipts.proto", fileDescriptor_ef1c006035b8d22c) }

var fileDescriptor_ef1c006035b8d22c = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5f, 0x6b, 0x13, 0x41,
	0x10, 0x27, 0xbd, 0x5c, 0x63, 0x26, 0x6d, 0x4d, 0xd7, 0x58, 0x16, 0x11, 0x09, 0x87, 0x48, 0x10,
	0x09, 0x5a, 0x5f, 0xfa, 0x5a, 0x52, 0x2b, 0x79, 0x89, 0xe9, 0x99, 0x3e, 0xcb, 0xf6, 0x76, 0xc0,
	0x85, 0xe4, 0xf6, 0xdc, 0xdd, 0x13, 0xf2, 0x11, 0xfc, 0x2a, 0x7e, 0x4a, 0x99, 0xd9, 0x6b, 0x72,
	0x81, 0x82, 0x6f, 0xf3, 0xfb, 0xcd, 0xec, 0xfc, 0xfd, 0x2d, 0x9c, 0x39, 0x2c, 0xd0, 0x54, 0xc1,
	0x4f, 0x2b, 0x67, 0x83, 0x15, 0x60, 0x4a, 0x6f, 0x34, 0xfe, 0x50, 0x95, 0xc9, 0xe6, 0x70, 0x7e,
	0xad, 0x75, 0x1e, 0x03, 0x72, 0xfc, 0x55, 0xa3, 0x0f, 0xe2, 0x02, 0x8e, 0x6b, 0x8f, 0x6e, 0xae,
	0x65, 0x67, 0xdc, 0x99, 0xf4, 0xf3, 0x06, 0x89, 0xd7, 0xd0, 0x6f, 0x52, 0xdd, 0x39, 0x79, 0xc4,
	0xae, 0x3d, 0x91, 0xbd, 0x07, 0xd1, 0x4e, 0xe5, 0x2b, 0x5b, 0x7a, 0x14, 0x23, 0x48, 0xd1, 0x39,
	0xeb, 0x9a, 0x54, 0x11, 0x64, 0x1f, 0x40, 0x7c, 0xc5, 0xd0, 0xc4, 0xfa, 0xff, 0xd4, 0xcd, 0xfe,
	0xa4, 0xd0, 0x6b, 0x62, 0xc5, 0x2b, 0x78, 0x76, 0xa3, 0x02, 0xae, 0xcc, 0x06, 0x39, 0x2a, 0xc9,
	0x77, 0x58, 0x64, 0x70, 0x32, 0x53, 0xfe, 0xe7, 0xca, 0x06, 0xb5, 0xfe, 0x5e, 0x6f, 0xb8, 0xc5,
	0x24, 0x3f, 0xe0, 0x84, 0x80, 0xee, 0xcc, 0x6a, 0x94, 0xc9, 0xb8, 0x33, 0x49, 0x73, 0xb6, 0x69,
	0xae, 0x99, 0x43, 0x6d, 0x02, 0x3d, 0xea, 0xf2, 0xa3, 0x3d, 0x21, 0xde, 0xc2, 0xe9, 0x97, 0xa2,
	0x9d, 0x36, 0xe5, 0x88, 0x43, 0x52, 0x5c, 0xc2, 0xe8, 0xd6, 0xf8, 0x42, 0xad, 0x6f, 0x6c, 0x51,
	0x6f, 0xb0, 0x0c, 0x8b, 0x7a, 0xf3, 0x80, 0x4e, 0x1e, 0x73, 0x9d, 0x27, 0x7d, 0x34, 0xef, 0x6d,
	0xe9, 0xef, 0xdd, 0x5a, 0xf6, 0xe3, 0xbc, 0x11, 0x89, 0x77, 0x90, 0xce, 0x03, 0x6e, 0xbc, 0x84,
	0x71, 0x32, 0x19, 0x5c, 0x0e, 0xa7, 0xfb, 0x83, 0x4d, 0xc9, 0x91, 0x47, 0xb7, 0x90, 0xd0, 0xbb,
	0xa7, 0x0d, 0x95, 0xa5, 0x1c, 0x70, 0x82, 0x47, 0x48, 0x5b, 0x5f, 0x68, 0xff, 0xe9, 0xa3, 0x3c,
	0xe1, 0x5e, 0x23, 0x78, 0x64, 0xaf, 0xe4, 0xe9, 0x9e, 0xbd, 0xa2, 0xf9, 0xbe, 0x55, 0xe8, 0x54,
	0x30, 0xb6, 0x5c, 0x6d, 0x2b, 0x94, 0x67, 0xdc, 0xf2, 0x21, 0x49, 0x7b, 0x8f, 0x84, 0x75, 0xf2,
	0x39, 0x17, 0xdb, 0x61, 0xf1, 0x06, 0x60, 0xe9, 0xb0, 0x52, 0x46, 0xd3, 0x7a, 0x86, 0x9c, 0xbc,
	0xc5, 0xd0, 0x5d, 0x96, 0xce, 0xfe, 0x36, 0xde, 0xd8, 0x92, 0x22, 0xce, 0xe3, 0x5d, 0xda, 0x1c,
	0x75, 0xd1, 0xc8, 0xa0, 0x59, 0x9c, 0x88, 0x5d, 0x1c, 0x90, 0x62, 0x0c, 0x83, 0x1c, 0x83, 0x32,
	0xeb, 0xe5, 0x5a, 0x15, 0x28, 0x5f, 0x70, 0x23, 0x6d, 0x4a, 0x4c, 0x41, 0xb4, 0xe0, 0xb5, 0xd6,
	0x0e, 0xbd, 0x97, 0x23, 0x0e, 0x7c, 0xc2, 0x43, 0x73, 0xed, 0x0e, 0xfb, 0x32, 0xea, 0xa9, 0xad,
	0x15, 0x5a, 0xa8, 0xbc, 0xe0, 0xd7, 0x6c, 0x67, 0x7f, 0x3b, 0xd0, 0xa5, 0xed, 0x93, 0x73, 0xa1,
	0x1a, 0x11, 0xf6, 0x73, 0xb6, 0xc5, 0x10, 0x92, 0x85, 0xf6, 0xac, 0xbb, 0x34, 0x27, 0x93, 0x4e,
	0xbc, 0xd0, 0x9e, 0x92, 0x27, 0x9c, 0xbc, 0x41, 0x34, 0xc8, 0x52, 0x6d, 0x49, 0x0b, 0xbc, 0xf2,
	0x2e, 0xbf, 0x68, 0x53, 0x74, 0xac, 0xa5, 0x33, 0x05, 0x36, 0x72, 0x8b, 0x80, 0xda, 0xbd, 0xab,
	0x55, 0x19, 0x4c, 0xd8, 0xb2, 0xb4, 0x8e, 0xf2, 0x1d, 0xa6, 0xea, 0x54, 0xa8, 0xc7, 0xf1, 0x64,
	0x3e, 0x1c, 0xf3, 0x87, 0xff, 0xfc, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xa7, 0x9e, 0x85, 0x02,
	0x04, 0x00, 0x00,
}
