// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: receipts.proto

package inside

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddReceiptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReceiptQr string `protobuf:"bytes,2,opt,name=receiptQr,proto3" json:"receiptQr,omitempty"`
}

func (x *AddReceiptRequest) Reset() {
	*x = AddReceiptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReceiptRequest) ProtoMessage() {}

func (x *AddReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReceiptRequest.ProtoReflect.Descriptor instead.
func (*AddReceiptRequest) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{0}
}

func (x *AddReceiptRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddReceiptRequest) GetReceiptQr() string {
	if x != nil {
		return x.ReceiptQr
	}
	return ""
}

type AddReceiptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddReceiptResponse) Reset() {
	*x = AddReceiptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReceiptResponse) ProtoMessage() {}

func (x *AddReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReceiptResponse.ProtoReflect.Descriptor instead.
func (*AddReceiptResponse) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{1}
}

func (x *AddReceiptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetReceiptsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetReceiptsRequest) Reset() {
	*x = GetReceiptsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReceiptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptsRequest) ProtoMessage() {}

func (x *GetReceiptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptsRequest.ProtoReflect.Descriptor instead.
func (*GetReceiptsRequest) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{2}
}

func (x *GetReceiptsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddRawTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Details *TicketDetails `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *AddRawTicketRequest) Reset() {
	*x = AddRawTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRawTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRawTicketRequest) ProtoMessage() {}

func (x *AddRawTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRawTicketRequest.ProtoReflect.Descriptor instead.
func (*AddRawTicketRequest) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{3}
}

func (x *AddRawTicketRequest) GetDetails() *TicketDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetRawReceiptReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Qr     string `protobuf:"bytes,2,opt,name=qr,proto3" json:"qr,omitempty"`
}

func (x *GetRawReceiptReportRequest) Reset() {
	*x = GetRawReceiptReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRawReceiptReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRawReceiptReportRequest) ProtoMessage() {}

func (x *GetRawReceiptReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRawReceiptReportRequest.ProtoReflect.Descriptor instead.
func (*GetRawReceiptReportRequest) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{4}
}

func (x *GetRawReceiptReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRawReceiptReportRequest) GetQr() string {
	if x != nil {
		return x.Qr
	}
	return ""
}

type RawReceiptReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Report   []byte `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *RawReceiptReport) Reset() {
	*x = RawReceiptReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawReceiptReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawReceiptReport) ProtoMessage() {}

func (x *RawReceiptReport) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawReceiptReport.ProtoReflect.Descriptor instead.
func (*RawReceiptReport) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{5}
}

func (x *RawReceiptReport) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *RawReceiptReport) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type Receipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateTime             int64   `protobuf:"varint,1,opt,name=DateTime,proto3" json:"DateTime,omitempty"`
	CashTotalSum         int64   `protobuf:"varint,2,opt,name=CashTotalSum,proto3" json:"CashTotalSum,omitempty"`
	Code                 int32   `protobuf:"varint,3,opt,name=Code,proto3" json:"Code,omitempty"`
	CreditSum            int64   `protobuf:"varint,4,opt,name=CreditSum,proto3" json:"CreditSum,omitempty"`
	EcashTotalSum        int64   `protobuf:"varint,5,opt,name=EcashTotalSum,proto3" json:"EcashTotalSum,omitempty"`
	FiscalDocumentNumber int32   `protobuf:"varint,6,opt,name=FiscalDocumentNumber,proto3" json:"FiscalDocumentNumber,omitempty"`
	FnsUrl               string  `protobuf:"bytes,9,opt,name=FnsUrl,proto3" json:"FnsUrl,omitempty"`
	Items                []*Item `protobuf:"bytes,10,rep,name=Items,proto3" json:"Items,omitempty"`
	UserInn              string  `protobuf:"bytes,11,opt,name=UserInn,proto3" json:"UserInn,omitempty"`
	Nds10                int64   `protobuf:"varint,12,opt,name=Nds10,proto3" json:"Nds10,omitempty"`
	Nds18                int64   `protobuf:"varint,13,opt,name=Nds18,proto3" json:"Nds18,omitempty"`
	OperationType        int32   `protobuf:"varint,14,opt,name=OperationType,proto3" json:"OperationType,omitempty"`
	Operator             string  `protobuf:"bytes,15,opt,name=Operator,proto3" json:"Operator,omitempty"`
	PrepaidSum           int64   `protobuf:"varint,16,opt,name=PrepaidSum,proto3" json:"PrepaidSum,omitempty"`
	ProvisionSum         int64   `protobuf:"varint,17,opt,name=ProvisionSum,proto3" json:"ProvisionSum,omitempty"`
	RequestNumber        int32   `protobuf:"varint,18,opt,name=RequestNumber,proto3" json:"RequestNumber,omitempty"`
	RetailPlace          string  `protobuf:"bytes,19,opt,name=RetailPlace,proto3" json:"RetailPlace,omitempty"`
	RetailPlaceAddress   string  `protobuf:"bytes,20,opt,name=RetailPlaceAddress,proto3" json:"RetailPlaceAddress,omitempty"`
	TotalSum             int64   `protobuf:"varint,21,opt,name=TotalSum,proto3" json:"TotalSum,omitempty"`
	User                 string  `protobuf:"bytes,22,opt,name=User,proto3" json:"User,omitempty"`
	PostpaymentSum       uint64  `protobuf:"varint,23,opt,name=PostpaymentSum,proto3" json:"PostpaymentSum,omitempty"`
	CounterSubmissionSum uint64  `protobuf:"varint,24,opt,name=CounterSubmissionSum,proto3" json:"CounterSubmissionSum,omitempty"`
	FiscalDriveNumber    string  `protobuf:"bytes,25,opt,name=FiscalDriveNumber,proto3" json:"FiscalDriveNumber,omitempty"`
	FiscalSign           uint32  `protobuf:"varint,26,opt,name=FiscalSign,proto3" json:"FiscalSign,omitempty"`
	KktRegId             string  `protobuf:"bytes,27,opt,name=KktRegId,proto3" json:"KktRegId,omitempty"`
	PrepaymentSum        uint64  `protobuf:"varint,28,opt,name=PrepaymentSum,proto3" json:"PrepaymentSum,omitempty"`
	ProtocolVersion      uint32  `protobuf:"varint,29,opt,name=ProtocolVersion,proto3" json:"ProtocolVersion,omitempty"`
	ReceiptCode          uint32  `protobuf:"varint,30,opt,name=ReceiptCode,proto3" json:"ReceiptCode,omitempty"`
	SenderAddress        string  `protobuf:"bytes,31,opt,name=SenderAddress,proto3" json:"SenderAddress,omitempty"`
	ShiftNumber          uint32  `protobuf:"varint,32,opt,name=ShiftNumber,proto3" json:"ShiftNumber,omitempty"`
	TaxationType         uint32  `protobuf:"varint,33,opt,name=TaxationType,proto3" json:"TaxationType,omitempty"`
	Id                   string  `protobuf:"bytes,34,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{6}
}

func (x *Receipt) GetDateTime() int64 {
	if x != nil {
		return x.DateTime
	}
	return 0
}

func (x *Receipt) GetCashTotalSum() int64 {
	if x != nil {
		return x.CashTotalSum
	}
	return 0
}

func (x *Receipt) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Receipt) GetCreditSum() int64 {
	if x != nil {
		return x.CreditSum
	}
	return 0
}

func (x *Receipt) GetEcashTotalSum() int64 {
	if x != nil {
		return x.EcashTotalSum
	}
	return 0
}

func (x *Receipt) GetFiscalDocumentNumber() int32 {
	if x != nil {
		return x.FiscalDocumentNumber
	}
	return 0
}

func (x *Receipt) GetFnsUrl() string {
	if x != nil {
		return x.FnsUrl
	}
	return ""
}

func (x *Receipt) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Receipt) GetUserInn() string {
	if x != nil {
		return x.UserInn
	}
	return ""
}

func (x *Receipt) GetNds10() int64 {
	if x != nil {
		return x.Nds10
	}
	return 0
}

func (x *Receipt) GetNds18() int64 {
	if x != nil {
		return x.Nds18
	}
	return 0
}

func (x *Receipt) GetOperationType() int32 {
	if x != nil {
		return x.OperationType
	}
	return 0
}

func (x *Receipt) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Receipt) GetPrepaidSum() int64 {
	if x != nil {
		return x.PrepaidSum
	}
	return 0
}

func (x *Receipt) GetProvisionSum() int64 {
	if x != nil {
		return x.ProvisionSum
	}
	return 0
}

func (x *Receipt) GetRequestNumber() int32 {
	if x != nil {
		return x.RequestNumber
	}
	return 0
}

func (x *Receipt) GetRetailPlace() string {
	if x != nil {
		return x.RetailPlace
	}
	return ""
}

func (x *Receipt) GetRetailPlaceAddress() string {
	if x != nil {
		return x.RetailPlaceAddress
	}
	return ""
}

func (x *Receipt) GetTotalSum() int64 {
	if x != nil {
		return x.TotalSum
	}
	return 0
}

func (x *Receipt) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Receipt) GetPostpaymentSum() uint64 {
	if x != nil {
		return x.PostpaymentSum
	}
	return 0
}

func (x *Receipt) GetCounterSubmissionSum() uint64 {
	if x != nil {
		return x.CounterSubmissionSum
	}
	return 0
}

func (x *Receipt) GetFiscalDriveNumber() string {
	if x != nil {
		return x.FiscalDriveNumber
	}
	return ""
}

func (x *Receipt) GetFiscalSign() uint32 {
	if x != nil {
		return x.FiscalSign
	}
	return 0
}

func (x *Receipt) GetKktRegId() string {
	if x != nil {
		return x.KktRegId
	}
	return ""
}

func (x *Receipt) GetPrepaymentSum() uint64 {
	if x != nil {
		return x.PrepaymentSum
	}
	return 0
}

func (x *Receipt) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Receipt) GetReceiptCode() uint32 {
	if x != nil {
		return x.ReceiptCode
	}
	return 0
}

func (x *Receipt) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *Receipt) GetShiftNumber() uint32 {
	if x != nil {
		return x.ShiftNumber
	}
	return 0
}

func (x *Receipt) GetTaxationType() uint32 {
	if x != nil {
		return x.TaxationType
	}
	return 0
}

func (x *Receipt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                   string  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Nds                    int32   `protobuf:"varint,2,opt,name=Nds,proto3" json:"Nds,omitempty"`
	NdsSum                 int64   `protobuf:"varint,3,opt,name=NdsSum,proto3" json:"NdsSum,omitempty"`
	PaymentType            int32   `protobuf:"varint,4,opt,name=PaymentType,proto3" json:"PaymentType,omitempty"`
	Price                  int64   `protobuf:"varint,5,opt,name=Price,proto3" json:"Price,omitempty"`
	Quantity               float32 `protobuf:"fixed32,6,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Sum                    int64   `protobuf:"varint,7,opt,name=Sum,proto3" json:"Sum,omitempty"`
	CalculationSubjectSign uint32  `protobuf:"varint,8,opt,name=CalculationSubjectSign,proto3" json:"CalculationSubjectSign,omitempty"`
	CalculationTypeSign    uint32  `protobuf:"varint,9,opt,name=CalculationTypeSign,proto3" json:"CalculationTypeSign,omitempty"`
	NdsRate                uint32  `protobuf:"varint,10,opt,name=NdsRate,proto3" json:"NdsRate,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{7}
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetNds() int32 {
	if x != nil {
		return x.Nds
	}
	return 0
}

func (x *Item) GetNdsSum() int64 {
	if x != nil {
		return x.NdsSum
	}
	return 0
}

func (x *Item) GetPaymentType() int32 {
	if x != nil {
		return x.PaymentType
	}
	return 0
}

func (x *Item) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetQuantity() float32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Item) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *Item) GetCalculationSubjectSign() uint32 {
	if x != nil {
		return x.CalculationSubjectSign
	}
	return 0
}

func (x *Item) GetCalculationTypeSign() uint32 {
	if x != nil {
		return x.CalculationTypeSign
	}
	return 0
}

func (x *Item) GetNdsRate() uint32 {
	if x != nil {
		return x.NdsRate
	}
	return 0
}

type Document struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receipt *Receipt `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
}

func (x *Document) Reset() {
	*x = Document{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{8}
}

func (x *Document) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type Ticket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Document *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{9}
}

func (x *Ticket) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type TicketDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       uint32        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Id           string        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Kind         string        `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	CreatedAt    string        `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Qr           string        `protobuf:"bytes,5,opt,name=qr,proto3" json:"qr,omitempty"`
	Operation    *Operation    `protobuf:"bytes,6,opt,name=operation,proto3" json:"operation,omitempty"`
	Process      []*Process    `protobuf:"bytes,7,rep,name=process,proto3" json:"process,omitempty"`
	Query        *Query        `protobuf:"bytes,8,opt,name=query,proto3" json:"query,omitempty"`
	Ticket       *Ticket       `protobuf:"bytes,9,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Organization *Organization `protobuf:"bytes,10,opt,name=organization,proto3" json:"organization,omitempty"`
	Seller       *Seller       `protobuf:"bytes,11,opt,name=seller,proto3" json:"seller,omitempty"`
}

func (x *TicketDetails) Reset() {
	*x = TicketDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketDetails) ProtoMessage() {}

func (x *TicketDetails) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketDetails.ProtoReflect.Descriptor instead.
func (*TicketDetails) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{10}
}

func (x *TicketDetails) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TicketDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TicketDetails) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TicketDetails) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TicketDetails) GetQr() string {
	if x != nil {
		return x.Qr
	}
	return ""
}

func (x *TicketDetails) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *TicketDetails) GetProcess() []*Process {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *TicketDetails) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *TicketDetails) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *TicketDetails) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *TicketDetails) GetSeller() *Seller {
	if x != nil {
		return x.Seller
	}
	return nil
}

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationType uint32 `protobuf:"varint,1,opt,name=operationType,proto3" json:"operationType,omitempty"`
	Sum           uint64 `protobuf:"varint,2,opt,name=sum,proto3" json:"sum,omitempty"`
	DocumentId    uint32 `protobuf:"varint,3,opt,name=documentId,proto3" json:"documentId,omitempty"`
	FsId          string `protobuf:"bytes,4,opt,name=fsId,proto3" json:"fsId,omitempty"`
	FiscalSign    string `protobuf:"bytes,5,opt,name=fiscalSign,proto3" json:"fiscalSign,omitempty"`
	Date          string `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{11}
}

func (x *Query) GetOperationType() uint32 {
	if x != nil {
		return x.OperationType
	}
	return 0
}

func (x *Query) GetSum() uint64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *Query) GetDocumentId() uint32 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

func (x *Query) GetFsId() string {
	if x != nil {
		return x.FsId
	}
	return ""
}

func (x *Query) GetFiscalSign() string {
	if x != nil {
		return x.FiscalSign
	}
	return ""
}

func (x *Query) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Organization struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Inn  string `protobuf:"bytes,2,opt,name=inn,proto3" json:"inn,omitempty"`
}

func (x *Organization) Reset() {
	*x = Organization{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{12}
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

type Seller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Inn  string `protobuf:"bytes,2,opt,name=inn,proto3" json:"inn,omitempty"`
}

func (x *Seller) Reset() {
	*x = Seller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seller) ProtoMessage() {}

func (x *Seller) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seller.ProtoReflect.Descriptor instead.
func (*Seller) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{13}
}

func (x *Seller) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Seller) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

type Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Type uint32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Sum  uint64 `protobuf:"varint,3,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *Operation) Reset() {
	*x = Operation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{14}
}

func (x *Operation) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Operation) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Operation) GetSum() uint64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type Process struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time   string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Result uint32 `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Process) Reset() {
	*x = Process{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_receipts_proto_rawDescGZIP(), []int{15}
}

func (x *Process) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Process) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_receipts_proto protoreflect.FileDescriptor

var file_receipts_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x49, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x51, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x51, 0x72, 0x22, 0x2a, 0x0a, 0x12, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x52, 0x61, 0x77, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x07,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x44, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x52, 0x61, 0x77,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x71, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x71, 0x72, 0x22, 0x46, 0x0a, 0x10,
	0x52, 0x61, 0x77, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb2, 0x08, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x43, 0x61, 0x73, 0x68, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x43, 0x61, 0x73, 0x68, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x6d,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x53, 0x75,
	0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x53,
	0x75, 0x6d, 0x12, 0x24, 0x0a, 0x0d, 0x45, 0x63, 0x61, 0x73, 0x68, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x53, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x45, 0x63, 0x61, 0x73, 0x68,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x6d, 0x12, 0x32, 0x0a, 0x14, 0x46, 0x69, 0x73, 0x63,
	0x61, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x46, 0x69, 0x73, 0x63, 0x61, 0x6c, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x46, 0x6e, 0x73, 0x55, 0x72, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x46, 0x6e,
	0x73, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x0a, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x6e, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x4e,
	0x64, 0x73, 0x31, 0x30, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4e, 0x64, 0x73, 0x31,
	0x30, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x64, 0x73, 0x31, 0x38, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x4e, 0x64, 0x73, 0x31, 0x38, 0x12, 0x24, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x69, 0x64, 0x53, 0x75, 0x6d, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x69, 0x64, 0x53, 0x75, 0x6d, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x18, 0x11, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x12, 0x24, 0x0a,
	0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x12,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x18, 0x13, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x14, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x12, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75,
	0x6d, 0x18, 0x15, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75,
	0x6d, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x16, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x74, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x6d, 0x18, 0x17, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x50,
	0x6f, 0x73, 0x74, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x6d, 0x12, 0x32, 0x0a,
	0x14, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x18, 0x18, 0x20, 0x01, 0x28, 0x04, 0x52, 0x14, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x75,
	0x6d, 0x12, 0x2c, 0x0a, 0x11, 0x46, 0x69, 0x73, 0x63, 0x61, 0x6c, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x19, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x46, 0x69,
	0x73, 0x63, 0x61, 0x6c, 0x44, 0x72, 0x69, 0x76, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1e, 0x0a, 0x0a, 0x46, 0x69, 0x73, 0x63, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x1a, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x46, 0x69, 0x73, 0x63, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x4b, 0x6b, 0x74, 0x52, 0x65, 0x67, 0x49, 0x64, 0x18, 0x1b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x4b, 0x6b, 0x74, 0x52, 0x65, 0x67, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x6d, 0x18, 0x1c, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0d, 0x50, 0x72, 0x65, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x75,
	0x6d, 0x12, 0x28, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x1d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x1f,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x68, 0x69, 0x66, 0x74, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x20, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x53, 0x68, 0x69, 0x66, 0x74, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x54, 0x61, 0x78, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x21, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x54, 0x61, 0x78,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x22, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0xae, 0x02, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x4e, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x64, 0x73, 0x53,
	0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4e, 0x64, 0x73, 0x53, 0x75, 0x6d,
	0x12, 0x20, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x51, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x75, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x53, 0x75, 0x6d, 0x12, 0x36, 0x0a, 0x16, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x69, 0x67, 0x6e,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x16, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x30,
	0x0a, 0x13, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x53, 0x69, 0x67, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x4e, 0x64, 0x73, 0x52, 0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x4e, 0x64, 0x73, 0x52, 0x61, 0x74, 0x65, 0x22, 0x2e, 0x0a, 0x08, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70,
	0x74, 0x52, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x22, 0x2f, 0x0a, 0x06, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xda, 0x02, 0x0a, 0x0d,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x71, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x71, 0x72, 0x12, 0x28, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x22, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x07, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x31, 0x0a, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65,
	0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72,
	0x52, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x22, 0xa7, 0x01, 0x0a, 0x05, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x73,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x73, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x66, 0x69, 0x73, 0x63, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x73, 0x63, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x22, 0x34, 0x0a, 0x0c, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6e, 0x6e, 0x22, 0x2e, 0x0a, 0x06, 0x53, 0x65, 0x6c, 0x6c,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6e, 0x6e, 0x22, 0x45, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x22,
	0x35, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x72, 0x79, 0x70, 0x61, 0x2f, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x69, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_receipts_proto_rawDescOnce sync.Once
	file_receipts_proto_rawDescData = file_receipts_proto_rawDesc
)

func file_receipts_proto_rawDescGZIP() []byte {
	file_receipts_proto_rawDescOnce.Do(func() {
		file_receipts_proto_rawDescData = protoimpl.X.CompressGZIP(file_receipts_proto_rawDescData)
	})
	return file_receipts_proto_rawDescData
}

var file_receipts_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_receipts_proto_goTypes = []interface{}{
	(*AddReceiptRequest)(nil),          // 0: AddReceiptRequest
	(*AddReceiptResponse)(nil),         // 1: AddReceiptResponse
	(*GetReceiptsRequest)(nil),         // 2: GetReceiptsRequest
	(*AddRawTicketRequest)(nil),        // 3: AddRawTicketRequest
	(*GetRawReceiptReportRequest)(nil), // 4: GetRawReceiptReportRequest
	(*RawReceiptReport)(nil),           // 5: RawReceiptReport
	(*Receipt)(nil),                    // 6: Receipt
	(*Item)(nil),                       // 7: Item
	(*Document)(nil),                   // 8: Document
	(*Ticket)(nil),                     // 9: Ticket
	(*TicketDetails)(nil),              // 10: TicketDetails
	(*Query)(nil),                      // 11: Query
	(*Organization)(nil),               // 12: Organization
	(*Seller)(nil),                     // 13: Seller
	(*Operation)(nil),                  // 14: Operation
	(*Process)(nil),                    // 15: Process
}
var file_receipts_proto_depIdxs = []int32{
	10, // 0: AddRawTicketRequest.details:type_name -> TicketDetails
	7,  // 1: Receipt.Items:type_name -> Item
	6,  // 2: Document.receipt:type_name -> Receipt
	8,  // 3: Ticket.document:type_name -> Document
	14, // 4: TicketDetails.operation:type_name -> Operation
	15, // 5: TicketDetails.process:type_name -> Process
	11, // 6: TicketDetails.query:type_name -> Query
	9,  // 7: TicketDetails.ticket:type_name -> Ticket
	12, // 8: TicketDetails.organization:type_name -> Organization
	13, // 9: TicketDetails.seller:type_name -> Seller
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_receipts_proto_init() }
func file_receipts_proto_init() {
	if File_receipts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_receipts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReceiptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReceiptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReceiptsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRawTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRawReceiptReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawReceiptReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Receipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Document); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ticket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Organization); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Operation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_receipts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_receipts_proto_goTypes,
		DependencyIndexes: file_receipts_proto_depIdxs,
		MessageInfos:      file_receipts_proto_msgTypes,
	}.Build()
	File_receipts_proto = out.File
	file_receipts_proto_rawDesc = nil
	file_receipts_proto_goTypes = nil
	file_receipts_proto_depIdxs = nil
}
