// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package inside

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReportApiClient is the client API for ReportApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportApiClient interface {
	GetReports(ctx context.Context, in *NoParams, opts ...grpc.CallOption) (ReportApi_GetReportsClient, error)
}

type reportApiClient struct {
	cc grpc.ClientConnInterface
}

func NewReportApiClient(cc grpc.ClientConnInterface) ReportApiClient {
	return &reportApiClient{cc}
}

func (c *reportApiClient) GetReports(ctx context.Context, in *NoParams, opts ...grpc.CallOption) (ReportApi_GetReportsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ReportApi_ServiceDesc.Streams[0], "/ReportApi/GetReports", opts...)
	if err != nil {
		return nil, err
	}
	x := &reportApiGetReportsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReportApi_GetReportsClient interface {
	Recv() (*Report, error)
	grpc.ClientStream
}

type reportApiGetReportsClient struct {
	grpc.ClientStream
}

func (x *reportApiGetReportsClient) Recv() (*Report, error) {
	m := new(Report)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReportApiServer is the server API for ReportApi service.
// All implementations must embed UnimplementedReportApiServer
// for forward compatibility
type ReportApiServer interface {
	GetReports(*NoParams, ReportApi_GetReportsServer) error
	mustEmbedUnimplementedReportApiServer()
}

// UnimplementedReportApiServer must be embedded to have forward compatible implementations.
type UnimplementedReportApiServer struct {
}

func (UnimplementedReportApiServer) GetReports(*NoParams, ReportApi_GetReportsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetReports not implemented")
}
func (UnimplementedReportApiServer) mustEmbedUnimplementedReportApiServer() {}

// UnsafeReportApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportApiServer will
// result in compilation errors.
type UnsafeReportApiServer interface {
	mustEmbedUnimplementedReportApiServer()
}

func RegisterReportApiServer(s grpc.ServiceRegistrar, srv ReportApiServer) {
	s.RegisterService(&ReportApi_ServiceDesc, srv)
}

func _ReportApi_GetReports_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NoParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReportApiServer).GetReports(m, &reportApiGetReportsServer{stream})
}

type ReportApi_GetReportsServer interface {
	Send(*Report) error
	grpc.ServerStream
}

type reportApiGetReportsServer struct {
	grpc.ServerStream
}

func (x *reportApiGetReportsServer) Send(m *Report) error {
	return x.ServerStream.SendMsg(m)
}

// ReportApi_ServiceDesc is the grpc.ServiceDesc for ReportApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ReportApi",
	HandlerType: (*ReportApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetReports",
			Handler:       _ReportApi_GetReports_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "report.proto",
}
