// Code generated by protoc-gen-go. DO NOT EDIT.
// source: requests.proto

package inside_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_undefined   Status = 0
	Status_checkPassed Status = 1
	Status_checkFailed Status = 2
	Status_requested   Status = 3
	Status_error       Status = 4
	Status_notFound    Status = 5
)

var Status_name = map[int32]string{
	0: "undefined",
	1: "checkPassed",
	2: "checkFailed",
	3: "requested",
	4: "error",
	5: "notFound",
}

var Status_value = map[string]int32{
	"undefined":   0,
	"checkPassed": 1,
	"checkFailed": 2,
	"requested":   3,
	"error":       4,
	"notFound":    5,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{0}
}

type ReceiptRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Qr                   string   `protobuf:"bytes,3,opt,name=qr,proto3" json:"qr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptRequest) Reset()         { *m = ReceiptRequest{} }
func (m *ReceiptRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiptRequest) ProtoMessage()    {}
func (*ReceiptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{0}
}

func (m *ReceiptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptRequest.Unmarshal(m, b)
}
func (m *ReceiptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptRequest.Marshal(b, m, deterministic)
}
func (m *ReceiptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptRequest.Merge(m, src)
}
func (m *ReceiptRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiptRequest.Size(m)
}
func (m *ReceiptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptRequest proto.InternalMessageInfo

func (m *ReceiptRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReceiptRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ReceiptRequest) GetQr() string {
	if m != nil {
		return m.Qr
	}
	return ""
}

type SetRequestStatusRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               Status   `protobuf:"varint,2,opt,name=status,proto3,enum=inside_api.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequestStatusRequest) Reset()         { *m = SetRequestStatusRequest{} }
func (m *SetRequestStatusRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequestStatusRequest) ProtoMessage()    {}
func (*SetRequestStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{1}
}

func (m *SetRequestStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequestStatusRequest.Unmarshal(m, b)
}
func (m *SetRequestStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequestStatusRequest.Marshal(b, m, deterministic)
}
func (m *SetRequestStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequestStatusRequest.Merge(m, src)
}
func (m *SetRequestStatusRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequestStatusRequest.Size(m)
}
func (m *SetRequestStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequestStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequestStatusRequest proto.InternalMessageInfo

func (m *SetRequestStatusRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetRequestStatusRequest) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_undefined
}

type SetStatusResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStatusResponse) Reset()         { *m = SetStatusResponse{} }
func (m *SetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*SetStatusResponse) ProtoMessage()    {}
func (*SetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9ccec99da7c9b4, []int{2}
}

func (m *SetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStatusResponse.Unmarshal(m, b)
}
func (m *SetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStatusResponse.Marshal(b, m, deterministic)
}
func (m *SetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStatusResponse.Merge(m, src)
}
func (m *SetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_SetStatusResponse.Size(m)
}
func (m *SetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetStatusResponse proto.InternalMessageInfo

func (m *SetStatusResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("inside_api.Status", Status_name, Status_value)
	proto.RegisterType((*ReceiptRequest)(nil), "inside_api.ReceiptRequest")
	proto.RegisterType((*SetRequestStatusRequest)(nil), "inside_api.SetRequestStatusRequest")
	proto.RegisterType((*SetStatusResponse)(nil), "inside_api.SetStatusResponse")
}

func init() { proto.RegisterFile("requests.proto", fileDescriptor_9c9ccec99da7c9b4) }

var fileDescriptor_9c9ccec99da7c9b4 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4f, 0x84, 0x30,
	0x10, 0x85, 0x85, 0x75, 0x89, 0x8c, 0x8a, 0x75, 0x62, 0x94, 0xa3, 0xe1, 0xa4, 0x7b, 0xe0, 0xa0,
	0xff, 0x61, 0xa3, 0x37, 0x03, 0xf1, 0x6c, 0x2a, 0x33, 0xc6, 0x46, 0xd3, 0x42, 0xa7, 0xfd, 0xff,
	0x66, 0xa1, 0xe2, 0xc9, 0xe3, 0xbc, 0x7c, 0xef, 0xcb, 0xe4, 0x41, 0xe5, 0x79, 0x8a, 0x2c, 0x41,
	0xda, 0xd1, 0xbb, 0xe0, 0x10, 0x8c, 0x15, 0x43, 0xfc, 0xa6, 0x47, 0xd3, 0x3c, 0x41, 0xd5, 0xf1,
	0xc0, 0x66, 0x0c, 0xdd, 0x02, 0x61, 0x05, 0xb9, 0xa1, 0x3a, 0xbb, 0xcd, 0xee, 0xca, 0x2e, 0x37,
	0x84, 0xd7, 0x50, 0x44, 0x61, 0xff, 0x4c, 0x75, 0x3e, 0x67, 0xe9, 0x3a, 0x70, 0x93, 0xaf, 0x37,
	0x0b, 0x37, 0xf9, 0xe6, 0x15, 0x6e, 0x7a, 0xfe, 0xb5, 0xf4, 0x41, 0x87, 0x28, 0xff, 0x29, 0x77,
	0x50, 0xc8, 0x0c, 0xcc, 0xca, 0xea, 0x01, 0xdb, 0xbf, 0x8f, 0xda, 0x54, 0x4d, 0x44, 0x73, 0x0f,
	0x97, 0x3d, 0xaf, 0x3e, 0x19, 0x9d, 0x15, 0xc6, 0x2b, 0xd8, 0xb2, 0xf7, 0xce, 0x27, 0xe7, 0x72,
	0xec, 0x34, 0x14, 0x0b, 0x87, 0xe7, 0x50, 0x46, 0x4b, 0xfc, 0x61, 0x2c, 0x93, 0x3a, 0xc2, 0x0b,
	0x38, 0x1d, 0x3e, 0x79, 0xf8, 0x7a, 0xd1, 0x22, 0x4c, 0x2a, 0x5b, 0x83, 0xbd, 0x36, 0xdf, 0x4c,
	0x2a, 0x3f, 0x14, 0xd2, 0x48, 0x4c, 0x6a, 0x83, 0x65, 0xf2, 0xab, 0x63, 0x3c, 0x83, 0x13, 0xeb,
	0xc2, 0xde, 0x45, 0x4b, 0x6a, 0xfb, 0x5e, 0xcc, 0x0b, 0x3e, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x50, 0xbd, 0x3b, 0xbc, 0x53, 0x01, 0x00, 0x00,
}
