version: '2'
services:
  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"
  mongo:
    image: mongo:4.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_SECRET}
    volumes:
      - "./data:/data/db"
    ports:
      - "27017:27017"
  nginx:
    image: nginx-gateway:dev
    ports:
      - "80:80"
