version: '2'

services:
  redis:
    image: redis:5.0.4

  mongo:
    image: mongo:4.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_SECRET}
    volumes:
      - "./data:/data/db"
    networks:
      - collector-net

  collector:
    build: .
    depends_on:
      - redis
      - mongo
    networks:
      - collector-net

  gateway:
    build: ./gateway
    ports:
      - "443:443"
    volumes:
      - "./ssl:/etc/nginx/ssl"
    networks:
      - collector-net
networks:
  collector-net:
