version: '2'
services:
  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"
  mongo:
    image: mongo:4.1
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=mongoadmin"
      - "MONGO_INITDB_ROOT_PASSWORD=secret"
    volumes:
      - "./data:/data/db"
    ports:
      - "27017:27017"
