version: '2'

services:
  redis:
    image: redis:5.0.4
    volumes:
      - redis-vol:/data
    networks:
      - collector-net

  mongo:
    image: mongo:4.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_SECRET}
    volumes:
      - mongo-vol:/data/db
    networks:
      - collector-net

  collector:
    build: .
    depends_on:
      - redis
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_LOGIN=${MONGO_LOGIN}
      - MONGO_SECRET=${MONGO_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NALOGRU_LOGIN=${NALOGRU_LOGIN}
      - NALOGRU_PASS=${NALOGRU_PASS}
    networks:
      - collector-net

  gateway:
    build: ./gateway
    ports:
      - "443:443"
    volumes:
      - "./ssl:/etc/nginx/ssl"
    networks:
      - collector-net
networks:
  collector-net:
volumes:
  redis-vol:
  mongo-vol:
