name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Backend
      run: cd ./backend
    - name: Publish Backend
      uses: elgohr/Publish-Docker-Github-Action@2.7
      with:
        name: drypa/receipt-collector:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
