name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Backend
      uses: elgohr/Publish-Docker-Github-Action@2.7
      with:
        name: drypa/receipt-collector
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
        workdir: backend
    - name: Publish Frontend
      uses: elgohr/Publish-Docker-Github-Action@2.7
      with:
        name: drypa/receipt-frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
        workdir: webapp
