name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Backend
      run: docker build . --file ./backend/Dockerfile --tag drypa/receipt-collector:$(date +%s)
