name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Backend
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: drypa/receipt-collector
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
        workdir: backend
        snapshot: true
    - name: Publish Frontend
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: drypa/receipt-frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
        workdir: webapp
        snapshot: true
    - name: Publish Telegram bot
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: drypa/receipt-telegram-bot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
        workdir: bot
        snapshot: true
